#!/bin/sh
# performs a spinning animation and conditional outcome based on given command
# run `conditional_status "checking bogus dir" "sleep 2; ls /bogus"` for demo
set -e

COL_NC='\e[0m'
COL_LIGHT_GREEN='\e[1;32m'
COL_LIGHT_RED='\e[1;31m'
SUCCESS="${COL_LIGHT_GREEN}*${COL_NC}"
FAILURE="${COL_LIGHT_RED}x${COL_NC}"
OVERWRITE='\r\033[K'

spinner_text(){
    spinner='| / - \ | / - \'

    while true; do
        for pos in $spinner; do
            printf "[ %s ] %s" "$pos" "$1"
            printf "%b[ %s ] %s" "$OVERWRITE" "$pos" "$1"
            sleep 0.1
        done
    done
}

overwrite_conditional_text(){
    if [ "$2" -eq 0 ]; then
        printf "%b[ %b ] %s" "$OVERWRITE" "$SUCCESS" "$1"
    else
        printf "%b[ %b ] %s" "$OVERWRITE" "$FAILURE" "$1"
    fi
}

changing_text(){
    text="$1"
    cmd="$2"
    spinner_text "$text" &
    SPIN_PID=$!
    trap "kill -9 $SPIN_PID" `seq 0 15`
    set +e
    eval $cmd >/dev/null 2>&1
    rc="$?"
    kill -9 $SPIN_PID
    overwrite_conditional_text "$text" $rc
    set -e
}

changing_text "$1" "$2"
