#!/usr/bin/env sh

# WARNING: this script cannot be used elswhere as the prompts dont pass through
# To use, copy the code and paste into own script
# `password_prompt $USER` will save the password to the $password variable

get_input(){
    stty -echo
    variable=''
    while [ -z "$variable" ]; do
        read variable
    done
    stty echo
    echo "$variable"
}

confirm_match(){
    confirmed=False
    while [ "$confirmed" = False ]; do
        if [ "$password" != "$confirmation" ]; then
            echo 'passwords do not match'
            password_prompt
            exit 0
        else
            confirmed=True
        fi
    done
}

password_prompt(){
    echo "enter password for $1: "
    password=$(get_input)
    echo "confirm pasword for $1: "
    confirmation=$(get_input)
    confirm_match
}

password_prompt $1

